# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(MMD), 1)
CFLAGS += -O0 -ggdb -DDEBUG -DDEBUG_NRF
CFLAGS += -DMMD
ASMFLAGS += -mcpu=cortex-m4
ASMFLAGS += -mthumb
OBJECTS += jlink_mmd/JLINK_MONITOR.o
OBJECTS += jlink_mmd/JLINK_MONITOR_ISR_SES.o
INCLUDE_PATHS += -I../jlink_mmd
$(info Building for monitor debug mode.)
endif

ifeq ($(HALT), 1)
CFLAGS += -O0 -ggdb -DDEBUG -DDEBUG_NRF
$(info Building for halt debug mode.)
endif

ifeq ($(RELEASE), 1)
CFLAGS += -O3 -g3
ASMFLAGS += -g3
$(info Building for release.)
endif

ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := nrf52_dk


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += main.o
OBJECTS += BLE_Button.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/startup_NRF52832.o

 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle_advertising.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle_discovery.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle_gap.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle_security.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/btle_security_pm.o
 SYS_OBJECTS += TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/btle/custom/custom_helper.o

INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I../TARGET_NRF52_DK
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_NRF52_DK
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/device
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/pwm
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/driver_nrf/saadc
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/headers/nrf52
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/hex
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_advertising
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_db_discovery
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_debug_assert_handler
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_dtm
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_error_log
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_racp
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_radio_notification
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_services
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/ble_services/ble_dfu
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/common
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/device_manager
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/device_manager/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/ble/peer_manager
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/device
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/ble_flash
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/clock
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/common
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/delay
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/gpiote
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/hal
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/ppi
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/pstorage
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/pstorage/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/spi_master
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/spi_slave
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/timer
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/drivers_nrf/twi_master
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/bootloader_dfu
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/bootloader_dfu/hci_transport
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/crc16
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/experimental_section_vars
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/fds
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/fds/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/fstorage
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/fstorage/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/hci
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/hci/config
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/pwm
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/scheduler
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/trace
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/libraries/util
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/softdevice
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/softdevice/common
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/sdk/softdevice/common/softdevice_handler
INCLUDE_PATHS += -I../TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM
INCLUDE_PATHS += -I../drivers
INCLUDE_PATHS += -I../hal
INCLUDE_PATHS += -I../platform
INCLUDE_PATHS += -I../rtos
INCLUDE_PATHS += -I../rtx
INCLUDE_PATHS += -I../rtx/TARGET_CORTEX_M
INCLUDE_PATHS += -I../src
INCLUDE_PATHS += -I../netsocket
INCLUDE_PATHS += -I../features
INCLUDE_PATHS += -I../features/FEATURE_BLE
INCLUDE_PATHS += -I../features/FEATURE_BLE/ble
INCLUDE_PATHS += -I../features/FEATURE_BLE/ble/services
INCLUDE_PATHS += -I../features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source
INCLUDE_PATHS += -I../features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle
INCLUDE_PATHS += -I../features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/btle/custom
INCLUDE_PATHS += -I../features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/common
INCLUDE_PATHS += -I../events
INCLUDE_PATHS += -I../events/equeue
INCLUDE_PATHS += -I../test

LIBRARY_PATHS := -L../TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM 
LIBRARIES := -l:libmbed-os.a
LINKER_SCRIPT ?= ../TARGET_NRF52_DK/TOOLCHAIN_GCC_ARM/NRF52832.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = 'arm-none-eabi-gcc' '-x' 'assembler-with-cpp' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CC      = 'arm-none-eabi-gcc' '-std=gnu99' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
CPP     = 'arm-none-eabi-g++' '-std=gnu++11' '-fno-rtti' '-Wvla' '-c' '-Wall' '-Wextra' '-Wno-unused-parameter' '-Wno-missing-field-initializers' '-fmessage-length=0' '-fno-exceptions' '-fno-builtin' '-ffunction-sections' '-fdata-sections' '-funsigned-char' '-MMD' '-fno-delete-null-pointer-checks' '-fomit-frame-pointer' '-O0' '-g3' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
LD      = 'arm-none-eabi-gcc' '-Wl,--gc-sections' '-mcpu=cortex-m4' '-mthumb' '-mfpu=fpv4-sp-d16' '-mfloat-abi=softfp'
ELF2BIN = 'arm-none-eabi-objcopy'

SREC_CAT = srec_cat

C_FLAGS += -std=gnu99
C_FLAGS += -DDEVICE_ERROR_PATTERN=1
C_FLAGS += -DTARGET_MCU_NRF52832
C_FLAGS += -DNRF52_PAN_51
C_FLAGS += -D__MBED__=1
C_FLAGS += -DNRF52_PAN_53
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1491729312.51
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DDEVICE_LOWPOWERTIMER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DTOOLCHAIN_object
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DBOARD_PCA10040
C_FLAGS += -DNRF52_PAN_12
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -DNRF52_PAN_58
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DNRF52_PAN_55
C_FLAGS += -DNRF52_PAN_54
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DTARGET_DEBUG
C_FLAGS += -DTARGET_NRF52_DK
C_FLAGS += -DNRF52_PAN_36
C_FLAGS += -DTARGET_LIKE_CORTEX_M4
C_FLAGS += -DTARGET_M4
C_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
C_FLAGS += -DTARGET_NRF5
C_FLAGS += -DFEATURE_BLE=1
C_FLAGS += -DTARGET_MCU_NRF52
C_FLAGS += -DNRF52_PAN_31
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DNRF52
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -DTARGET_NRF52832
C_FLAGS += -D__CORTEX_M4
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DNRF52_PAN_63
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DCONFIG_GPIO_AS_PINRESET
C_FLAGS += -DTARGET_NORDIC
C_FLAGS += -DNRF52_PAN_30
C_FLAGS += -DBLE_STACK_SUPPORT_REQD
C_FLAGS += -DNRF52_PAN_15
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DSWI_DISABLE0
C_FLAGS += -DNRF52_PAN_20
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DNRF52_PAN_64
C_FLAGS += -DSOFTDEVICE_PRESENT
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DNRF52_PAN_62
C_FLAGS += -DS132
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DARM_MATH_CM4
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -include
C_FLAGS += mbed_config.h

CXX_FLAGS += -std=gnu++11
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -DDEVICE_ERROR_PATTERN=1
CXX_FLAGS += -DTARGET_MCU_NRF52832
CXX_FLAGS += -DNRF52_PAN_51
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DNRF52_PAN_53
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1491729312.51
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DDEVICE_LOWPOWERTIMER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DTOOLCHAIN_object
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DBOARD_PCA10040
CXX_FLAGS += -DNRF52_PAN_12
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -DNRF52_PAN_58
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DNRF52_PAN_55
CXX_FLAGS += -DNRF52_PAN_54
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DTARGET_DEBUG
CXX_FLAGS += -DTARGET_NRF52_DK
CXX_FLAGS += -DNRF52_PAN_36
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M4
CXX_FLAGS += -DTARGET_M4
CXX_FLAGS += -DTARGET_UVISOR_UNSUPPORTED
CXX_FLAGS += -DTARGET_NRF5
CXX_FLAGS += -DFEATURE_BLE=1
CXX_FLAGS += -DTARGET_MCU_NRF52
CXX_FLAGS += -DNRF52_PAN_31
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DNRF52
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -DTARGET_NRF52832
CXX_FLAGS += -D__CORTEX_M4
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DNRF52_PAN_63
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DCONFIG_GPIO_AS_PINRESET
CXX_FLAGS += -DTARGET_NORDIC
CXX_FLAGS += -DNRF52_PAN_30
CXX_FLAGS += -DBLE_STACK_SUPPORT_REQD
CXX_FLAGS += -DNRF52_PAN_15
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DSWI_DISABLE0
CXX_FLAGS += -DNRF52_PAN_20
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DNRF52_PAN_64
CXX_FLAGS += -DSOFTDEVICE_PRESENT
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DNRF52_PAN_62
CXX_FLAGS += -DS132
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DARM_MATH_CM4
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h

ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DNRF52
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DBOARD_PCA10040
ASM_FLAGS += -DNRF52_PAN_12
ASM_FLAGS += -DNRF52_PAN_15
ASM_FLAGS += -DNRF52_PAN_58
ASM_FLAGS += -DNRF52_PAN_55
ASM_FLAGS += -DNRF52_PAN_54
ASM_FLAGS += -DARM_MATH_CM4
ASM_FLAGS += -DNRF52_PAN_30
ASM_FLAGS += -DNRF52_PAN_51
ASM_FLAGS += -DNRF52_PAN_36
ASM_FLAGS += -DNRF52_PAN_53
ASM_FLAGS += -DTARGET_NRF52832
ASM_FLAGS += -D__CORTEX_M4
ASM_FLAGS += -DNRF52_PAN_63
ASM_FLAGS += -DCONFIG_GPIO_AS_PINRESET
ASM_FLAGS += -DBLE_STACK_SUPPORT_REQD
ASM_FLAGS += -DSWI_DISABLE0
ASM_FLAGS += -DNRF52_PAN_20
ASM_FLAGS += -DNRF52_PAN_64
ASM_FLAGS += -DSOFTDEVICE_PRESENT
ASM_FLAGS += -DNRF52_PAN_62
ASM_FLAGS += -DS132
ASM_FLAGS += -DNRF52_PAN_31


LD_FLAGS :=-Wl,--gc-sections -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size

all: $(PROJECT).bin $(PROJECT)-combined.hex size


.asm.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

#.s.o:
#	+@$(call MAKEDIR,$(dir $@))
#	+@echo "Assemble: $(notdir $<)"
#	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

#.S.o:
#	+@$(call MAKEDIR,$(dir $@))
#	+@echo "Assemble: $(notdir $<)"
#	@$(AS) -c $(ASM_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(LINKER_SCRIPT)
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter %.ld, $^) $(LIBRARY_PATHS) --output $@ $(filter %.o, $^) $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@


$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


$(PROJECT)-combined.hex: $(PROJECT).hex
	+@echo "NOTE: the $(SREC_CAT) binary is required to be present in your PATH. Please see http://srecord.sourceforge.net/ for more information."
	$(SREC_CAT) ../TARGET_NRF52_DK/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/softdevice/s132/hex/s132_nrf52_2.0.0_softdevice.hex  -intel $(PROJECT).hex -intel -o $(PROJECT)-combined.hex -intel --line-length=44
	+@echo "===== hex file ready to flash: $(OBJDIR)/$@ ====="

# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
